# Generated by Django 4.1.7 on 2023-04-11 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircrafts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a aircraft name.', max_length=255, verbose_name='Aircraft name')),
                ('country', models.CharField(help_text='Enter a country name that owns the aircraft.', max_length=255, verbose_name='Country name that owns the aircraft')),
                ('comment', models.TextField(blank=True, help_text='Enter comment for aircraft.', null=True, verbose_name='Aircraft comment')),
            ],
            options={
                'verbose_name': 'Aircraft',
                'verbose_name_plural': 'Aircrafts',
            },
        ),
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a cargo name.', max_length=255, verbose_name='Cargo name')),
                ('quantity', models.PositiveIntegerField(help_text='Enter a cargo quantity.', verbose_name='Cargo quantity')),
                ('comment', models.TextField(blank=True, help_text='Enter comment for cargo', null=True, verbose_name='Cargo comment')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_airport', models.CharField(help_text='Enter a airport name from the plane will take off.', max_length=255, verbose_name='Airport name from the plane will take off')),
                ('to_airport', models.CharField(help_text='Enter a airport name where the plane will land.', max_length=255, verbose_name='Airport name where the plane will land')),
                ('scheduled_take_off', models.DateTimeField(help_text='Select a scheduled take off date and time.')),
                ('scheduled_landing', models.DateTimeField(help_text='Select a scheduled landing date and time.')),
                ('comment', models.TextField(blank=True, help_text='Enter comment for destination.', null=True, verbose_name='Destination comment')),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
            },
        ),
        migrations.CreateModel(
            name='Pilots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter a pilot first name.', max_length=255, verbose_name='Pilot first name')),
                ('last_name', models.CharField(help_text='Enter a pilot last name.', max_length=255, verbose_name='Pilot last name')),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='airlift.aircrafts')),
            ],
            options={
                'verbose_name': 'Pilot information',
                'verbose_name_plural': 'Pilots informations',
            },
        ),
        migrations.CreateModel(
            name='PilotsInformations',
            fields=[
                ('pilot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='airlift.pilots')),
                ('position', models.CharField(help_text='Enter a pilot position.', max_length=255, verbose_name='Pilot position')),
                ('rank', models.CharField(help_text='Enter a pilot rank.', max_length=255, verbose_name='Pilot rank')),
                ('age', models.PositiveSmallIntegerField(help_text='Enter a pilot age.', verbose_name='Pilot age')),
                ('country', models.CharField(help_text='Enter a pilot country.', max_length=255, verbose_name='Pilot country')),
                ('comment', models.TextField(blank=True, help_text='Enter comment for pilot.', null=True, verbose_name='Pilot comment')),
            ],
            options={
                'verbose_name': 'Pilot additional information',
                'verbose_name_plural': 'Pilot additional informations',
            },
        ),
        migrations.AddField(
            model_name='aircrafts',
            name='cargo',
            field=models.ManyToManyField(blank=True, to='airlift.cargos'),
        ),
        migrations.AddField(
            model_name='aircrafts',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='airlift.destinations'),
        ),
    ]
